# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Server.create(name:"BASIC1")
Server.create(name:"STD1")
Server.create(name:"STD2")
Server.create(name:"STD3")
Server.create(name:"PREMIUM1")
Server.create(name:"PREMIUM2")
Server.create(name:"PREMIUM3")
Server.create(name:"PREMIUM4")
Server.create(name:"PREMIUM5")
Server.create(name:"PREMIUM6")
Server.create(name:"PREMIUM7")
Server.create(name:"PREMIUM9")
Server.create(name:"PREMIUM10")
Server.create(name:"PREMIUM11")
Server.create(name:"PREMIUM12")
Server.create(name:"PREMIUM13")
Server.create(name:"PREMIUM14")
Server.create(name:"PREMIUM15")
Server.create(name:"SCRAPEBOX1")
Server.create(name:"NINGUNO")

OrderStatus.create(name:"Lista_Anadir")
OrderStatus.create(name:"Pend_Articulos")
OrderStatus.create(name:"Pend_Informacion")
OrderStatus.create(name:"Planificada")
OrderStatus.create(name:"Por_Entregar")
OrderStatus.create(name:"Entregada")
OrderStatus.create(name:"Art_Por_Aprobar")
OrderStatus.create(name:"Enviada_Pablo")
OrderStatus.create(name:"Por_Planificar")
OrderStatus.create(name:"Cancelada")
OrderStatus.create(name:"SolicitudCancelacion")
OrderStatus.create(name:"ExtensionSolicitada")

OrderType.create(name:"PR9_BASIC")
OrderType.create(name:"PR9_STANDARD")
OrderType.create(name:"PR9_PREMIUM")
OrderType.create(name:"TRAFFIC_BASIC")
OrderType.create(name:"TRAFFIC_STANDARD")
OrderType.create(name:"TRAFFIC_PREMIUM")
OrderType.create(name:"CUSTOM_OFFER")
OrderType.create(name:"ON_PAGE_FIX")
OrderType.create(name:"BLOG_CONTENT_WRITE")

ExtrasStatus.create(name:"No_Entregado")
ExtrasStatus.create(name:"Entregado")
ExtrasStatus.create(name:"En_Proceso")
ExtrasStatus.create(name:"No lleva")

Writer.create(name:"NINGUNO")
Writer.create(name:"Anindita")
Writer.create(name:"April")
Writer.create(name:"Mahnoor")
Writer.create(name:"Prince")

Writingstatus.create(status:"Por_Escribir")
Writingstatus.create(status:"En_Proceso")
Writingstatus.create(status:"Enviado_Al_Cliente")
Writingstatus.create(status:"En_Proceso")
Writingstatus.create(status:"Aprobado")
Writingstatus.create(status:"Rechazado")
